-- De csv-files zijn exports vanuit de volgende SQL-query's:

-- Klant+leeftijd:
-- SELECT *, DATEDIFF(YEAR, GEBOORTEDATUM, GETDATE()) AS LEEFTIJD FROM KLANT

-- Artikel+categorie:
-- SELECT A.BARCODE, A.MERK, A.TYPE, A.TITEL, A.SPEL_OF_CONSOLE, S.CATEGORIE FROM ARTIKEL A
-- LEFT JOIN SPEL S ON A.TITEL = S.TITEL
-- WHERE A.BARCODE NOT IN (SELECT K.BARCODE FROM KOOPOVEREENKOMST K)
